name: Update Guide Files

on:
  workflow_dispatch:

jobs:
  update-guides:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests pytz

      - name: Run guide fetch script
        run: python p.py

      - name: Generate index.json
        run: |
          python <<EOF
          import os
          import json

          directory = 'output/guides'
          os.makedirs(directory, exist_ok=True)
          files = [f for f in os.listdir(directory) if f.endswith('.json') and f != 'index.json']
          files.sort()
          with open(os.path.join(directory, 'index.json'), 'w', encoding='utf-8') as f:
              json.dump(files, f, indent=2)
          print(f'Creato index.json con {len(files)} file')
          EOF

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add output/guides/
          if git diff --cached --quiet; then
            echo "Nessun cambiamento da commitare"
          else
            git commit -m "Aggiornamento automatico guide [skip ci]"
            git push
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
