name: Generate Guide Index

on:
  workflow_dispatch:
  push:
    paths:
      - 'output/guides/*.json'
      - '!output/guides/index.json'

jobs:
  generate_index:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Generate index.json
        run: |
          python <<EOF
          import os
          import json

          directory = "output/guides"
          if not os.path.exists(directory):
              print(f"La directory {directory} non esiste")
              exit(1)

          files = [f for f in os.listdir(directory) if f.endswith(".json") and f != "index.json"]
          files.sort()

          with open(os.path.join(directory, "index.json"), "w", encoding="utf-8") as f:
              json.dump(files, f, indent=2, ensure_ascii=False)

          print(f"Creato index.json con {len(files)} file elencati")
          EOF

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add output/guides/index.json
          if git diff --cached --quiet; then
            echo "Nessun cambiamento da commitare"
          else
            git commit -m "Aggiornato index.json automaticamente"
            git push
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
