name: Fetch TV Guides

on:
  schedule:
    # Ogni 7 giorni, alle 2:00 UTC (puoi cambiare)
    - cron: '0 2 */7 * *'

  workflow_dispatch: # permette di avviare manualmente

jobs:
  fetch-guides:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests pytz

      - name: Run fetch script
        run: python fetch_guides.py

      - name: Commit and push guides
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add guides/
          git commit -m "Aggiornamento automatico guida TV $(date +'%Y-%m-%d')"
          git push
        env:
          # Se usi un token personalizzato, definiscilo qui:
          # GITHUB_TOKEN: ${{ secrets.GITHUB_
          TOKEN }}
