name: Fetch Guides Everyday

on:
  schedule:
    - cron: '0 0 */1 * *'  # Ogni giorno a mezzanotte UTC
  workflow_dispatch:       # Permette avvio manuale

jobs:
  fetch-guides:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytz requests aiohttp beautifulsoup4

      - name: Run fetch_guides.py
        run: |
          echo "🟢 Inizio esecuzione fetch_guides.py"
          python fetch_guides.py
          echo "✅ fetch_guides.py completato con successo"

      - name: List output files
        run: |
          echo "Contenuto della cartella output/guides:"
          ls -la output/guides || echo "Cartella output/guides non trovata"

      - name: Commit and push updated guides.json
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add output
          git diff --cached --quiet || git commit -m "Updated guides - $(date +'%Y-%m-%d')"
          git pull --rebase origin main
          git push origin HEAD:main
