name: Fetch Guides Everyday

on:
  schedule:
    - cron: '0 0 */1 * *'  # Ogni giorno a mezzanotte UTC
  workflow_dispatch:       # Permette avvio manuale

jobs:
  fetch-guides:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytz requests aiohttp beautifulsoup4

      - name: Run fetch_guides.py
        run: python fetch_guides.py

      - name: Commit and push updated guides.json
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add output
          git diff --cached --quiet || git commit -m "Update guide.json - $(date +'%Y-%m-%d')"
          git pull --rebase origin main
          git push origin HEAD:main
