name: Fetch Guides Every 2 Days

on:
  schedule:
    - cron: '0 0 */2 * *'  # Ogni 2 giorni a mezzanotte UTC
  workflow_dispatch:        # Permette anche avvio manuale

jobs:
  fetch-guides:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytz requests aiohttp beautifulsoup4

      - name: Debug working directory
        run: |
          echo "游릭 Working directory: $(pwd)"
          echo "游릭 Listing files:"
          ls -la

      - name: Run fetch_guides.py
        run: |
          set -e
          echo "游릭 Running fetch_guides.py..."
          python fetch_guides.py

      - name: Commit and push updated guides
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add output

          # Commit solo se ci sono modifiche
          if git diff --cached --quiet; then
            echo "游릭 Nessuna modifica da commitare."
          else
            git commit -m "Update guides - $(date +'%Y-%m-%d')"
            git pull --rebase origin main
            git push origin HEAD:main
          fi
